FROM ruby:3-bullseye

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /api
WORKDIR /api

ADD Gemfile /api/Gemfile
ADD Gemfile.lock /api/Gemfile.lock

RUN bundle install 

ADD . /api

COPY bin/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
